name: Volte CI

on:
  push:
    branches:
    - v3
  pull_request:
    branches:
    - v3

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100-preview3-010431'
    - name: build the damn thing
      run: bash build.sh
    - name: upload linux binary
      uses: actions/upload-artifact@master
      with:
        name: Volte-Linux
        path: src/bin/Release/netcoreapp3.0/linux-x64/publish
    - name: upload windows binary
      uses: actions/upload-artifact@master
      with:
        name: Volte-Windows
        path: src/bin/Release/netcoreapp3.0/win10-x64/publish